mod error;
mod openai_chat_completions;
mod types;

pub use error::ModelError;
pub use error::ModelErrorKind;
pub use openai_chat_completions::OpenAiChatCompletionsProvider;
pub use types::BoxModelFuture;
pub use types::ModelEvent;
pub use types::ModelInstruction;
pub use types::ModelInstructionSource;
pub use types::ModelMessage;
pub use types::ModelProvider;
pub use types::ModelRequest;
pub use types::ModelRole;
pub use types::ModelStream;
pub use types::ModelToolCall;
pub use types::ModelToolDefinition;
pub use types::ModelUsage;
pub use types::WORKSPACE_ROOT_AGENTS_INSTRUCTION_PREFIX;
