mod discovery;
mod error;
mod native;
mod openai_chat_completions;
mod tool_names;
mod types;

pub use discovery::DiscoveredModel;
pub use discovery::ModelDiscoveryProtocol;
pub use discovery::discover_models;
pub use error::ModelError;
pub use error::ModelErrorKind;
pub use native::NativeModelProvider;
pub use native::append_path;
pub use openai_chat_completions::OpenAiChatCompletionsProvider;
pub use types::BoxModelFuture;
pub use types::ModelEvent;
pub use types::ModelInstruction;
pub use types::ModelInstructionSource;
pub use types::ModelMessage;
pub use types::ModelOutputItem;
pub use types::ModelOutputItemKind;
pub use types::ModelProvider;
pub use types::ModelRequest;
pub use types::ModelResponse;
pub use types::ModelRole;
pub use types::ModelStream;
pub use types::ModelTextPhase;
pub use types::ModelToolCall;
pub use types::ModelToolDefinition;
pub use types::ModelUsage;
pub use types::WORKSPACE_AGENTS_HIERARCHY_INSTRUCTION_PREFIX;
pub use types::WORKSPACE_ROOT_AGENTS_INSTRUCTION_PREFIX;
