[package]
name = "sugarcode-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "sugarcode"
path = "src/main.rs"

[dependencies]
clap.workspace = true
sugarcode-app-server = { path = "../app-server" }
sugarcode-app-server-protocol = { path = "../app-server-protocol" }
sugarcode-state = { path = "../state" }
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
