export const MIN_MODEL_REQUEST_TIMEOUT_MS = 60_000;
export const DEFAULT_MODEL_REQUEST_TIMEOUT_MS = 600_000;
export const MAX_MODEL_REQUEST_TIMEOUT_MS = 3_600_000;

export const MODEL_REQUEST_ATTEMPT_TIMEOUT_MS =
  DEFAULT_MODEL_REQUEST_TIMEOUT_MS;
