[package]
name = "sugarcode-app-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
base64.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
sugarcode-agent-runtime = { path = "../agent-runtime" }
sugarcode-app-server-protocol = { path = "../app-server-protocol" }
sugarcode-core = { path = "../core" }
sugarcode-protocol = { path = "../protocol" }
sugarcode-state = { path = "../state" }
sugarcode-tools = { path = "../tools" }
tokio.workspace = true

[dev-dependencies]
git2.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util"] }
