use crate::ClientInfo;
use crate::InitializeCapabilities;
use crate::InitializeParams;
use crate::InitializeResponse;
use crate::JsonRpcError;
use crate::JsonRpcErrorObject;
use crate::JsonRpcMessage;
use crate::JsonRpcNotification;
use crate::JsonRpcRequest;
use crate::JsonRpcResponse;
use crate::JsonRpcVersion;
use crate::PlatformInfo;
use crate::RequestId;
use crate::ServerCapabilities;
use crate::ServerInfo;
use schemars::schema_for;
use std::fs;
use std::io;
use std::path::Path;
use ts_rs::TS;

const GENERATED_HEADER: &str = "// Generated by sugarcode. Do not edit by hand.\n\n";

pub fn generate_typescript(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;

    let declarations = [
        JsonRpcVersion::decl(),
        RequestId::decl(),
        JsonRpcRequest::decl(),
        JsonRpcNotification::decl(),
        JsonRpcResponse::decl(),
        JsonRpcErrorObject::decl(),
        JsonRpcError::decl(),
        JsonRpcMessage::decl(),
        ClientInfo::decl(),
        InitializeCapabilities::decl(),
        InitializeParams::decl(),
        ServerInfo::decl(),
        PlatformInfo::decl(),
        ServerCapabilities::decl(),
        InitializeResponse::decl(),
    ];

    let mut protocol = String::from(GENERATED_HEADER);
    protocol.push_str(
        "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n",
    );
    for declaration in declarations {
        protocol.push_str("export ");
        protocol.push_str(&declaration);
        protocol.push_str("\n\n");
    }
    fs::write(out_dir.join("protocol.ts"), protocol)?;
    fs::write(
        out_dir.join("index.ts"),
        format!("{GENERATED_HEADER}export * from './protocol';\n"),
    )?;
    Ok(())
}

pub fn generate_json_schema(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;
    write_schema(
        out_dir.join("JsonRpcMessage.schema.json"),
        &schema_for!(JsonRpcMessage),
    )?;
    write_schema(
        out_dir.join("InitializeParams.schema.json"),
        &schema_for!(InitializeParams),
    )?;
    write_schema(
        out_dir.join("InitializeResponse.schema.json"),
        &schema_for!(InitializeResponse),
    )
}

fn write_schema(path: impl AsRef<Path>, schema: &impl serde::Serialize) -> io::Result<()> {
    let bytes = serde_json::to_vec_pretty(schema).map_err(io::Error::other)?;
    fs::write(path, [bytes, b"\n".to_vec()].concat())
}
