use crate::AgentMessageDeltaNotification;
use crate::ClientInfo;
use crate::InitializeCapabilities;
use crate::InitializeParams;
use crate::InitializeResponse;
use crate::Item;
use crate::ItemCompletedNotification;
use crate::ItemStartedNotification;
use crate::JsonRpcError;
use crate::JsonRpcErrorObject;
use crate::JsonRpcMessage;
use crate::JsonRpcNotification;
use crate::JsonRpcRequest;
use crate::JsonRpcResponse;
use crate::JsonRpcVersion;
use crate::PlatformInfo;
use crate::RequestId;
use crate::ServerCapabilities;
use crate::ServerInfo;
use crate::Thread;
use crate::ThreadArchiveParams;
use crate::ThreadArchiveResponse;
use crate::ThreadListParams;
use crate::ThreadListResponse;
use crate::ThreadResumeParams;
use crate::ThreadResumeResponse;
use crate::ThreadSearchParams;
use crate::ThreadSearchResponse;
use crate::ThreadStartParams;
use crate::ThreadStartResponse;
use crate::ThreadStartedNotification;
use crate::Turn;
use crate::TurnCompletedNotification;
use crate::TurnSnapshot;
use crate::TurnSnapshotStatus;
use crate::TurnStartParams;
use crate::TurnStartResponse;
use crate::TurnStartedNotification;
use crate::TurnStatus;
use schemars::schema_for;
use std::fs;
use std::io;
use std::path::Path;
use ts_rs::TS;

const GENERATED_HEADER: &str = "// Generated by sugarcode. Do not edit by hand.\n\n";

pub fn generate_typescript(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;

    let declarations = [
        JsonRpcVersion::decl(),
        RequestId::decl(),
        JsonRpcRequest::decl(),
        JsonRpcNotification::decl(),
        JsonRpcResponse::decl(),
        JsonRpcErrorObject::decl(),
        JsonRpcError::decl(),
        JsonRpcMessage::decl(),
        ClientInfo::decl(),
        InitializeCapabilities::decl(),
        InitializeParams::decl(),
        ServerInfo::decl(),
        PlatformInfo::decl(),
        ServerCapabilities::decl(),
        InitializeResponse::decl(),
        Item::decl(),
        ItemStartedNotification::decl(),
        AgentMessageDeltaNotification::decl(),
        ItemCompletedNotification::decl(),
        Thread::decl(),
        ThreadArchiveParams::decl(),
        ThreadArchiveResponse::decl(),
        ThreadListParams::decl(),
        ThreadListResponse::decl(),
        ThreadSearchParams::decl(),
        ThreadSearchResponse::decl(),
        ThreadStartParams::decl(),
        ThreadStartResponse::decl(),
        ThreadStartedNotification::decl(),
        ThreadResumeParams::decl(),
        TurnSnapshotStatus::decl(),
        TurnSnapshot::decl(),
        ThreadResumeResponse::decl(),
        Turn::decl(),
        TurnStatus::decl(),
        TurnStartParams::decl(),
        TurnStartResponse::decl(),
        TurnStartedNotification::decl(),
        TurnCompletedNotification::decl(),
    ];

    let mut protocol = String::from(GENERATED_HEADER);
    protocol.push_str(
        "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n",
    );
    protocol.push_str(&format!(
        "export const JSON_RPC_VERSION = {:?} as const;\n\n",
        crate::JSON_RPC_VERSION
    ));
    protocol.push_str(&format!(
        "export const PROTOCOL_VERSION = {} as const;\n\n",
        crate::PROTOCOL_VERSION
    ));
    protocol.push_str(&format!(
        "export const SUGARCODE_PRODUCT_VERSION = {:?} as const;\n\n",
        crate::SUGARCODE_PRODUCT_VERSION
    ));
    for declaration in declarations {
        protocol.push_str("export ");
        protocol.push_str(&declaration);
        protocol.push_str("\n\n");
    }
    fs::write(out_dir.join("protocol.ts"), protocol)?;
    fs::write(
        out_dir.join("index.ts"),
        format!("{GENERATED_HEADER}export * from './protocol';\n"),
    )?;
    Ok(())
}

pub fn generate_json_schema(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;
    write_schema(
        out_dir.join("JsonRpcMessage.schema.json"),
        &schema_for!(JsonRpcMessage),
    )?;
    write_schema(
        out_dir.join("InitializeParams.schema.json"),
        &schema_for!(InitializeParams),
    )?;
    write_schema(
        out_dir.join("InitializeResponse.schema.json"),
        &schema_for!(InitializeResponse),
    )?;
    write_schema(out_dir.join("Item.schema.json"), &schema_for!(Item))?;
    write_schema(
        out_dir.join("ItemStartedNotification.schema.json"),
        &schema_for!(ItemStartedNotification),
    )?;
    write_schema(
        out_dir.join("AgentMessageDeltaNotification.schema.json"),
        &schema_for!(AgentMessageDeltaNotification),
    )?;
    write_schema(
        out_dir.join("ItemCompletedNotification.schema.json"),
        &schema_for!(ItemCompletedNotification),
    )?;
    write_schema(out_dir.join("Thread.schema.json"), &schema_for!(Thread))?;
    write_schema(
        out_dir.join("ThreadArchiveParams.schema.json"),
        &schema_for!(ThreadArchiveParams),
    )?;
    write_schema(
        out_dir.join("ThreadArchiveResponse.schema.json"),
        &schema_for!(ThreadArchiveResponse),
    )?;
    write_schema(
        out_dir.join("ThreadListParams.schema.json"),
        &schema_for!(ThreadListParams),
    )?;
    write_schema(
        out_dir.join("ThreadListResponse.schema.json"),
        &schema_for!(ThreadListResponse),
    )?;
    write_schema(
        out_dir.join("ThreadSearchParams.schema.json"),
        &schema_for!(ThreadSearchParams),
    )?;
    write_schema(
        out_dir.join("ThreadSearchResponse.schema.json"),
        &schema_for!(ThreadSearchResponse),
    )?;
    write_schema(
        out_dir.join("ThreadStartParams.schema.json"),
        &schema_for!(ThreadStartParams),
    )?;
    write_schema(
        out_dir.join("ThreadStartResponse.schema.json"),
        &schema_for!(ThreadStartResponse),
    )?;
    write_schema(
        out_dir.join("ThreadStartedNotification.schema.json"),
        &schema_for!(ThreadStartedNotification),
    )?;
    write_schema(
        out_dir.join("ThreadResumeParams.schema.json"),
        &schema_for!(ThreadResumeParams),
    )?;
    write_schema(
        out_dir.join("TurnSnapshotStatus.schema.json"),
        &schema_for!(TurnSnapshotStatus),
    )?;
    write_schema(
        out_dir.join("TurnSnapshot.schema.json"),
        &schema_for!(TurnSnapshot),
    )?;
    write_schema(
        out_dir.join("ThreadResumeResponse.schema.json"),
        &schema_for!(ThreadResumeResponse),
    )?;
    write_schema(out_dir.join("Turn.schema.json"), &schema_for!(Turn))?;
    write_schema(
        out_dir.join("TurnStartParams.schema.json"),
        &schema_for!(TurnStartParams),
    )?;
    write_schema(
        out_dir.join("TurnStartResponse.schema.json"),
        &schema_for!(TurnStartResponse),
    )?;
    write_schema(
        out_dir.join("TurnStartedNotification.schema.json"),
        &schema_for!(TurnStartedNotification),
    )?;
    write_schema(
        out_dir.join("TurnCompletedNotification.schema.json"),
        &schema_for!(TurnCompletedNotification),
    )
}

fn write_schema(path: impl AsRef<Path>, schema: &impl serde::Serialize) -> io::Result<()> {
    let bytes = serde_json::to_vec_pretty(schema).map_err(io::Error::other)?;
    fs::write(path, [bytes, b"\n".to_vec()].concat())
}
