use crate::AgentMessageDeltaNotification;
use crate::AgentOutputDeltaNotification;
use crate::AgentOutputRef;
use crate::AgentTaskAccess;
use crate::AgentTaskRole;
use crate::AgentTaskStatus;
use crate::ApprovalSourceAgent;
use crate::ClientInfo;
use crate::CommandApprovalParams;
use crate::CommandApprovalResponse;
use crate::CommandApprovalResponseDecision;
use crate::CommandNetworkPolicy;
use crate::CommandSandboxPolicy;
use crate::CommandWorkspaceWritePolicy;
use crate::CommandWorkspaceWriteRisk;
use crate::ContextCompactionOutcome;
use crate::ContextCompactionStrategy;
use crate::FileChangeKind;
use crate::FileChangeNewlineStyle;
use crate::InitializeCapabilities;
use crate::InitializeParams;
use crate::InitializeResponse;
use crate::Item;
use crate::ItemCompletedNotification;
use crate::ItemStartedNotification;
use crate::JsonRpcError;
use crate::JsonRpcErrorObject;
use crate::JsonRpcMessage;
use crate::JsonRpcNotification;
use crate::JsonRpcRequest;
use crate::JsonRpcResponse;
use crate::JsonRpcVersion;
use crate::McpToolCallApprovalParams;
use crate::McpToolCallApprovalResponse;
use crate::McpToolCallApprovalResponseDecision;
use crate::McpToolResult;
use crate::PlatformInfo;
use crate::ProcessOutcome;
use crate::RequestId;
use crate::ServerCapabilities;
use crate::ServerInfo;
use crate::Thread;
use crate::ThreadArchiveParams;
use crate::ThreadArchiveResponse;
use crate::ThreadDeleteParams;
use crate::ThreadDeleteResponse;
use crate::ThreadDescendantsListParams;
use crate::ThreadDescendantsListResponse;
use crate::ThreadForkParams;
use crate::ThreadForkResponse;
use crate::ThreadListParams;
use crate::ThreadListResponse;
use crate::ThreadOrigin;
use crate::ThreadResumeParams;
use crate::ThreadResumeResponse;
use crate::ThreadSearchParams;
use crate::ThreadSearchResponse;
use crate::ThreadStartParams;
use crate::ThreadStartResponse;
use crate::ThreadStartedNotification;
use crate::ThreadUnarchiveParams;
use crate::ThreadUnarchiveResponse;
use crate::ToolResult;
use crate::Turn;
use crate::TurnCompletedNotification;
use crate::TurnError;
use crate::TurnErrorKind;
use crate::TurnInterruptParams;
use crate::TurnInterruptResponse;
use crate::TurnSnapshot;
use crate::TurnSnapshotStatus;
use crate::TurnStartParams;
use crate::TurnStartResponse;
use crate::TurnStartedNotification;
use crate::TurnStatus;
use crate::WorkspaceBinding;
use crate::WorkspaceEntry;
use crate::WorkspaceEntryKind;
use crate::WorkspaceGitChangeKind;
use crate::WorkspaceGitCommitParams;
use crate::WorkspaceGitCommitResponse;
use crate::WorkspaceGitDiffParams;
use crate::WorkspaceGitDiffResponse;
use crate::WorkspaceGitDiffSource;
use crate::WorkspaceGitErrorKind;
use crate::WorkspaceGitMutationParams;
use crate::WorkspaceGitMutationResponse;
use crate::WorkspaceGitRepositoryState;
use crate::WorkspaceGitStatusEntry;
use crate::WorkspaceGitStatusParams;
use crate::WorkspaceGitStatusResponse;
use crate::WorkspaceInspectErrorKind;
use crate::WorkspaceInspectParams;
use crate::WorkspaceInspectResponse;
use crate::WorkspaceListParams;
use crate::WorkspaceListResponse;
use schemars::schema_for;
use std::fs;
use std::io;
use std::path::Path;
use ts_rs::TS;

const GENERATED_HEADER: &str = "// Generated by sugarcode. Do not edit by hand.\n\n";

pub fn generate_typescript(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;

    let declarations = [
        JsonRpcVersion::decl(),
        RequestId::decl(),
        JsonRpcRequest::decl(),
        JsonRpcNotification::decl(),
        JsonRpcResponse::decl(),
        JsonRpcErrorObject::decl(),
        JsonRpcError::decl(),
        JsonRpcMessage::decl(),
        ClientInfo::decl(),
        InitializeCapabilities::decl(),
        InitializeParams::decl(),
        ServerInfo::decl(),
        PlatformInfo::decl(),
        ServerCapabilities::decl(),
        WorkspaceBinding::decl(),
        InitializeResponse::decl(),
        CommandApprovalResponseDecision::decl(),
        CommandNetworkPolicy::decl(),
        CommandSandboxPolicy::decl(),
        CommandWorkspaceWritePolicy::decl(),
        CommandWorkspaceWriteRisk::decl(),
        ApprovalSourceAgent::decl(),
        CommandApprovalParams::decl(),
        CommandApprovalResponse::decl(),
        McpToolCallApprovalResponseDecision::decl(),
        McpToolCallApprovalParams::decl(),
        McpToolCallApprovalResponse::decl(),
        FileChangeKind::decl(),
        FileChangeNewlineStyle::decl(),
        ProcessOutcome::decl(),
        ToolResult::decl(),
        McpToolResult::decl(),
        ContextCompactionStrategy::decl(),
        ContextCompactionOutcome::decl(),
        AgentTaskRole::decl(),
        AgentTaskAccess::decl(),
        AgentTaskStatus::decl(),
        Item::decl(),
        AgentOutputRef::decl(),
        ItemStartedNotification::decl(),
        AgentOutputDeltaNotification::decl(),
        AgentMessageDeltaNotification::decl(),
        ItemCompletedNotification::decl(),
        Thread::decl(),
        ThreadOrigin::decl(),
        ThreadArchiveParams::decl(),
        ThreadArchiveResponse::decl(),
        ThreadDeleteParams::decl(),
        ThreadDeleteResponse::decl(),
        ThreadDescendantsListParams::decl(),
        ThreadDescendantsListResponse::decl(),
        ThreadForkParams::decl(),
        ThreadForkResponse::decl(),
        ThreadUnarchiveParams::decl(),
        ThreadUnarchiveResponse::decl(),
        ThreadListParams::decl(),
        ThreadListResponse::decl(),
        ThreadSearchParams::decl(),
        ThreadSearchResponse::decl(),
        ThreadStartParams::decl(),
        ThreadStartResponse::decl(),
        ThreadStartedNotification::decl(),
        ThreadResumeParams::decl(),
        TurnSnapshotStatus::decl(),
        TurnSnapshot::decl(),
        ThreadResumeResponse::decl(),
        Turn::decl(),
        TurnStatus::decl(),
        TurnErrorKind::decl(),
        TurnError::decl(),
        TurnStartParams::decl(),
        TurnStartResponse::decl(),
        TurnStartedNotification::decl(),
        TurnCompletedNotification::decl(),
        TurnInterruptParams::decl(),
        TurnInterruptResponse::decl(),
        WorkspaceEntryKind::decl(),
        WorkspaceEntry::decl(),
        WorkspaceListParams::decl(),
        WorkspaceListResponse::decl(),
        WorkspaceInspectErrorKind::decl(),
        WorkspaceInspectParams::decl(),
        WorkspaceInspectResponse::decl(),
        WorkspaceGitChangeKind::decl(),
        WorkspaceGitRepositoryState::decl(),
        WorkspaceGitErrorKind::decl(),
        WorkspaceGitStatusEntry::decl(),
        WorkspaceGitStatusParams::decl(),
        WorkspaceGitStatusResponse::decl(),
        WorkspaceGitDiffSource::decl(),
        WorkspaceGitDiffParams::decl(),
        WorkspaceGitDiffResponse::decl(),
        WorkspaceGitMutationParams::decl(),
        WorkspaceGitMutationResponse::decl(),
        WorkspaceGitCommitParams::decl(),
        WorkspaceGitCommitResponse::decl(),
    ];

    let mut protocol = String::from(GENERATED_HEADER);
    protocol.push_str(
        "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };\n\n",
    );
    protocol.push_str(&format!(
        "export const JSON_RPC_VERSION = {:?} as const;\n\n",
        crate::JSON_RPC_VERSION
    ));
    protocol.push_str(&format!(
        "export const PROTOCOL_VERSION = {} as const;\n\n",
        crate::PROTOCOL_VERSION
    ));
    protocol.push_str(&format!(
        "export const SUGARCODE_PRODUCT_VERSION = {:?} as const;\n\n",
        crate::SUGARCODE_PRODUCT_VERSION
    ));
    for declaration in declarations {
        protocol.push_str("export ");
        protocol.push_str(&declaration);
        protocol.push_str("\n\n");
    }
    fs::write(out_dir.join("protocol.ts"), protocol)?;
    fs::write(
        out_dir.join("index.ts"),
        format!("{GENERATED_HEADER}export * from './protocol';\n"),
    )?;
    Ok(())
}

pub fn generate_json_schema(out_dir: &Path) -> io::Result<()> {
    fs::create_dir_all(out_dir)?;
    write_schema(
        out_dir.join("JsonRpcMessage.schema.json"),
        &schema_for!(JsonRpcMessage),
    )?;
    write_schema(
        out_dir.join("InitializeParams.schema.json"),
        &schema_for!(InitializeParams),
    )?;
    write_schema(
        out_dir.join("InitializeResponse.schema.json"),
        &schema_for!(InitializeResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceListParams.schema.json"),
        &schema_for!(WorkspaceListParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceListResponse.schema.json"),
        &schema_for!(WorkspaceListResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceInspectParams.schema.json"),
        &schema_for!(WorkspaceInspectParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceInspectResponse.schema.json"),
        &schema_for!(WorkspaceInspectResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitStatusParams.schema.json"),
        &schema_for!(WorkspaceGitStatusParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitStatusResponse.schema.json"),
        &schema_for!(WorkspaceGitStatusResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitDiffParams.schema.json"),
        &schema_for!(WorkspaceGitDiffParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitDiffResponse.schema.json"),
        &schema_for!(WorkspaceGitDiffResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitMutationParams.schema.json"),
        &schema_for!(WorkspaceGitMutationParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitMutationResponse.schema.json"),
        &schema_for!(WorkspaceGitMutationResponse),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitCommitParams.schema.json"),
        &schema_for!(WorkspaceGitCommitParams),
    )?;
    write_schema(
        out_dir.join("WorkspaceGitCommitResponse.schema.json"),
        &schema_for!(WorkspaceGitCommitResponse),
    )?;
    write_schema(
        out_dir.join("CommandApprovalParams.schema.json"),
        &schema_for!(CommandApprovalParams),
    )?;
    write_schema(
        out_dir.join("ApprovalSourceAgent.schema.json"),
        &schema_for!(ApprovalSourceAgent),
    )?;
    write_schema(
        out_dir.join("CommandApprovalResponse.schema.json"),
        &schema_for!(CommandApprovalResponse),
    )?;
    write_schema(
        out_dir.join("McpToolCallApprovalParams.schema.json"),
        &schema_for!(McpToolCallApprovalParams),
    )?;
    write_schema(
        out_dir.join("McpToolCallApprovalResponse.schema.json"),
        &schema_for!(McpToolCallApprovalResponse),
    )?;
    write_schema(
        out_dir.join("FileChangeKind.schema.json"),
        &schema_for!(FileChangeKind),
    )?;
    write_schema(
        out_dir.join("FileChangeNewlineStyle.schema.json"),
        &schema_for!(FileChangeNewlineStyle),
    )?;
    write_schema(
        out_dir.join("ToolResult.schema.json"),
        &schema_for!(ToolResult),
    )?;
    write_schema(
        out_dir.join("McpToolResult.schema.json"),
        &schema_for!(McpToolResult),
    )?;
    write_schema(
        out_dir.join("ContextCompactionStrategy.schema.json"),
        &schema_for!(ContextCompactionStrategy),
    )?;
    write_schema(
        out_dir.join("ContextCompactionOutcome.schema.json"),
        &schema_for!(ContextCompactionOutcome),
    )?;
    write_schema(
        out_dir.join("AgentTaskRole.schema.json"),
        &schema_for!(AgentTaskRole),
    )?;
    write_schema(
        out_dir.join("AgentTaskAccess.schema.json"),
        &schema_for!(AgentTaskAccess),
    )?;
    write_schema(
        out_dir.join("AgentTaskStatus.schema.json"),
        &schema_for!(AgentTaskStatus),
    )?;
    write_schema(out_dir.join("Item.schema.json"), &schema_for!(Item))?;
    write_schema(
        out_dir.join("AgentOutputRef.schema.json"),
        &schema_for!(AgentOutputRef),
    )?;
    write_schema(
        out_dir.join("ItemStartedNotification.schema.json"),
        &schema_for!(ItemStartedNotification),
    )?;
    write_schema(
        out_dir.join("AgentOutputDeltaNotification.schema.json"),
        &schema_for!(AgentOutputDeltaNotification),
    )?;
    write_schema(
        out_dir.join("AgentMessageDeltaNotification.schema.json"),
        &schema_for!(AgentMessageDeltaNotification),
    )?;
    write_schema(
        out_dir.join("ItemCompletedNotification.schema.json"),
        &schema_for!(ItemCompletedNotification),
    )?;
    write_schema(out_dir.join("Thread.schema.json"), &schema_for!(Thread))?;
    write_schema(
        out_dir.join("ThreadOrigin.schema.json"),
        &schema_for!(ThreadOrigin),
    )?;
    write_schema(
        out_dir.join("ThreadArchiveParams.schema.json"),
        &schema_for!(ThreadArchiveParams),
    )?;
    write_schema(
        out_dir.join("ThreadArchiveResponse.schema.json"),
        &schema_for!(ThreadArchiveResponse),
    )?;
    write_schema(
        out_dir.join("ThreadDeleteParams.schema.json"),
        &schema_for!(ThreadDeleteParams),
    )?;
    write_schema(
        out_dir.join("ThreadDeleteResponse.schema.json"),
        &schema_for!(ThreadDeleteResponse),
    )?;
    write_schema(
        out_dir.join("ThreadDescendantsListParams.schema.json"),
        &schema_for!(ThreadDescendantsListParams),
    )?;
    write_schema(
        out_dir.join("ThreadDescendantsListResponse.schema.json"),
        &schema_for!(ThreadDescendantsListResponse),
    )?;
    write_schema(
        out_dir.join("ThreadForkParams.schema.json"),
        &schema_for!(ThreadForkParams),
    )?;
    write_schema(
        out_dir.join("ThreadForkResponse.schema.json"),
        &schema_for!(ThreadForkResponse),
    )?;
    write_schema(
        out_dir.join("ThreadUnarchiveParams.schema.json"),
        &schema_for!(ThreadUnarchiveParams),
    )?;
    write_schema(
        out_dir.join("ThreadUnarchiveResponse.schema.json"),
        &schema_for!(ThreadUnarchiveResponse),
    )?;
    write_schema(
        out_dir.join("ThreadListParams.schema.json"),
        &schema_for!(ThreadListParams),
    )?;
    write_schema(
        out_dir.join("ThreadListResponse.schema.json"),
        &schema_for!(ThreadListResponse),
    )?;
    write_schema(
        out_dir.join("ThreadSearchParams.schema.json"),
        &schema_for!(ThreadSearchParams),
    )?;
    write_schema(
        out_dir.join("ThreadSearchResponse.schema.json"),
        &schema_for!(ThreadSearchResponse),
    )?;
    write_schema(
        out_dir.join("ThreadStartParams.schema.json"),
        &schema_for!(ThreadStartParams),
    )?;
    write_schema(
        out_dir.join("ThreadStartResponse.schema.json"),
        &schema_for!(ThreadStartResponse),
    )?;
    write_schema(
        out_dir.join("ThreadStartedNotification.schema.json"),
        &schema_for!(ThreadStartedNotification),
    )?;
    write_schema(
        out_dir.join("ThreadResumeParams.schema.json"),
        &schema_for!(ThreadResumeParams),
    )?;
    write_schema(
        out_dir.join("TurnSnapshotStatus.schema.json"),
        &schema_for!(TurnSnapshotStatus),
    )?;
    write_schema(
        out_dir.join("TurnSnapshot.schema.json"),
        &schema_for!(TurnSnapshot),
    )?;
    write_schema(
        out_dir.join("ThreadResumeResponse.schema.json"),
        &schema_for!(ThreadResumeResponse),
    )?;
    write_schema(out_dir.join("Turn.schema.json"), &schema_for!(Turn))?;
    write_schema(
        out_dir.join("TurnStartParams.schema.json"),
        &schema_for!(TurnStartParams),
    )?;
    write_schema(
        out_dir.join("TurnStartResponse.schema.json"),
        &schema_for!(TurnStartResponse),
    )?;
    write_schema(
        out_dir.join("TurnStartedNotification.schema.json"),
        &schema_for!(TurnStartedNotification),
    )?;
    write_schema(
        out_dir.join("TurnCompletedNotification.schema.json"),
        &schema_for!(TurnCompletedNotification),
    )?;
    write_schema(
        out_dir.join("TurnInterruptParams.schema.json"),
        &schema_for!(TurnInterruptParams),
    )?;
    write_schema(
        out_dir.join("TurnInterruptResponse.schema.json"),
        &schema_for!(TurnInterruptResponse),
    )
}

fn write_schema(path: impl AsRef<Path>, schema: &impl serde::Serialize) -> io::Result<()> {
    let bytes = serde_json::to_vec_pretty(schema).map_err(io::Error::other)?;
    fs::write(path, [bytes, b"\n".to_vec()].concat())
}
