mod approval;
mod asset;
mod export;
mod initialize;
mod item;
mod mcp;
mod rpc;
mod thread;
mod turn;
mod workspace;
mod workspace_git;

pub use asset::AssetDescriptor;
pub use asset::AssetImportParams;
pub use asset::AssetImportResponse;
pub use asset::AssetKind;
pub use asset::MAX_ASSET_IMPORT_BASE64_BYTES;
pub use export::generate_json_schema;
pub use export::generate_typescript;
pub use initialize::ClientInfo;
pub use initialize::InitializeCapabilities;
pub use initialize::InitializeParams;
pub use initialize::InitializeResponse;
pub use initialize::PlatformInfo;
pub use initialize::ServerCapabilities;
pub use initialize::ServerInfo;
pub use initialize::WorkspaceBinding;
pub use item::AgentMessageDeltaNotification;
pub use item::AgentOutputDeltaNotification;
pub use item::AgentOutputRef;
pub use item::AgentTaskAccess;
pub use item::AgentTaskRole;
pub use item::AgentTaskStatus;
pub use item::ContextCompactionOutcome;
pub use item::ContextCompactionStrategy;
pub use item::FileChangeKind;
pub use item::FileChangeNewlineStyle;
pub use item::Item;
pub use item::ItemCompletedNotification;
pub use item::ItemStartedNotification;
pub use item::McpToolResult;
pub use item::ProcessOutcome;
pub use item::ToolResult;
pub use mcp::McpToolCallApprovalParams;
pub use mcp::McpToolCallApprovalResponse;
pub use mcp::McpToolCallApprovalResponseDecision;
pub use rpc::JsonRpcError;
pub use rpc::JsonRpcErrorObject;
pub use rpc::JsonRpcMessage;
pub use rpc::JsonRpcNotification;
pub use rpc::JsonRpcRequest;
pub use rpc::JsonRpcResponse;
pub use rpc::JsonRpcVersion;
pub use rpc::RequestId;
pub use thread::DEFAULT_THREAD_LIST_LIMIT;
pub use thread::DEFAULT_THREAD_SEARCH_LIMIT;
pub use thread::MAX_THREAD_LIST_LIMIT;
pub use thread::MAX_THREAD_SEARCH_LIMIT;
pub use thread::MAX_THREAD_SEARCH_QUERY_BYTES;
pub use thread::MAX_THREAD_SEARCH_QUERY_TERMS;
pub use thread::Thread;
pub use thread::ThreadArchiveParams;
pub use thread::ThreadArchiveResponse;
pub use thread::ThreadDeleteParams;
pub use thread::ThreadDeleteResponse;
pub use thread::ThreadDescendantsListParams;
pub use thread::ThreadDescendantsListResponse;
pub use thread::ThreadForkParams;
pub use thread::ThreadForkResponse;
pub use thread::ThreadListParams;
pub use thread::ThreadListResponse;
pub use thread::ThreadOrigin;
pub use thread::ThreadResumeParams;
pub use thread::ThreadResumeResponse;
pub use thread::ThreadSearchParams;
pub use thread::ThreadSearchResponse;
pub use thread::ThreadStartParams;
pub use thread::ThreadStartResponse;
pub use thread::ThreadStartedNotification;
pub use thread::ThreadUnarchiveParams;
pub use thread::ThreadUnarchiveResponse;
pub use thread::TurnSnapshot;
pub use thread::TurnSnapshotStatus;
pub use turn::MAX_TURN_ATTACHMENT_BYTES;
pub use turn::MAX_TURN_ATTACHMENTS;
pub use turn::MAX_TURN_INPUT_BYTES;
pub use turn::ModelProviderFamily;
pub use turn::ModelSelectionCapabilities;
pub use turn::ModelSelectionSnapshot;
pub use turn::ModelWireApi;
pub use turn::ProviderErrorMetadata;
pub use turn::TokenUsage;
pub use turn::TokenUsageSample;
pub use turn::TokenUsageSource;
pub use turn::TokenUsageUpdatedNotification;
pub use turn::ToolSchemaError;
pub use turn::Turn;
pub use turn::TurnCompletedNotification;
pub use turn::TurnError;
pub use turn::TurnErrorKind;
pub use turn::TurnInputPart;
pub use turn::TurnInterruptParams;
pub use turn::TurnInterruptResponse;
pub use turn::TurnStartParams;
pub use turn::TurnStartResponse;
pub use turn::TurnStartedNotification;
pub use turn::TurnStatus;
pub use turn::TurnWarningCode;
pub use turn::TurnWarningNotification;
pub use workspace::WorkspaceEntry;
pub use workspace::WorkspaceEntryKind;
pub use workspace::WorkspaceInspectErrorKind;
pub use workspace::WorkspaceInspectParams;
pub use workspace::WorkspaceInspectResponse;
pub use workspace::WorkspaceListParams;
pub use workspace::WorkspaceListResponse;
pub use workspace_git::WorkspaceGitChangeKind;
pub use workspace_git::WorkspaceGitCommitParams;
pub use workspace_git::WorkspaceGitCommitResponse;
pub use workspace_git::WorkspaceGitDiffParams;
pub use workspace_git::WorkspaceGitDiffResponse;
pub use workspace_git::WorkspaceGitDiffSource;
pub use workspace_git::WorkspaceGitErrorKind;
pub use workspace_git::WorkspaceGitMutationParams;
pub use workspace_git::WorkspaceGitMutationResponse;
pub use workspace_git::WorkspaceGitRepositoryState;
pub use workspace_git::WorkspaceGitStatusEntry;
pub use workspace_git::WorkspaceGitStatusParams;
pub use workspace_git::WorkspaceGitStatusResponse;

pub const JSON_RPC_VERSION: &str = "2.0";
pub const PROTOCOL_VERSION: u32 = 1;
pub const SUGARCODE_PRODUCT_VERSION: &str = env!("CARGO_PKG_VERSION");

pub const ERROR_PARSE: i32 = -32700;
pub const ERROR_INVALID_REQUEST: i32 = -32600;
pub const ERROR_METHOD_NOT_FOUND: i32 = -32601;
pub const ERROR_INVALID_PARAMS: i32 = -32602;
pub const ERROR_INTERNAL: i32 = -32603;
pub const ERROR_UNSUPPORTED_PROTOCOL_VERSION: i32 = -32000;
pub const ERROR_NOT_INITIALIZED: i32 = -32001;
pub const ERROR_ALREADY_INITIALIZED: i32 = -32002;
pub const ERROR_DUPLICATE_REQUEST: i32 = -32003;
pub const ERROR_THREAD_NOT_FOUND: i32 = -32004;
pub const ERROR_STATE_UNAVAILABLE: i32 = -32005;
pub const ERROR_TURN_NOT_FOUND: i32 = -32006;
pub const ERROR_MODEL_UNAVAILABLE: i32 = -32007;
pub const ERROR_TURN_NOT_ACTIVE: i32 = -32008;
pub const ERROR_TURN_ACTIVE: i32 = -32009;
pub const ERROR_WORKSPACE_UNAVAILABLE: i32 = -32010;
pub use approval::ApprovalSourceAgent;
pub use approval::CommandApprovalParams;
pub use approval::CommandApprovalResponse;
pub use approval::CommandApprovalResponseDecision;
pub use approval::CommandNetworkPolicy;
pub use approval::CommandSandboxPolicy;
pub use approval::CommandWorkspaceWritePolicy;
pub use approval::CommandWorkspaceWriteRisk;
